#!/bin/bash

PRJ="neminfo"
PROD_HOST="www@node"
PROD_PATH="/www/$PRJ"
PROD_ROOT=$PROD_HOST:$PROD_PATH

UBERJAR="tmp/target/$PRJ.jar"

ssh $PROD_HOST mkdir -p $PROD_PATH/var
# scp var/* $PROD_ROOT/var/
scp run-loop start stop tmp/prod.edn $PROD_ROOT/

chmod u+w $UBERJAR
scp $UBERJAR $PROD_ROOT/

ssh $PROD_HOST $PROD_PATH/stop

#.
